from __future__ import annotations

from enum import Enum


class SessionState(str, Enum):
    CREATED     = "CREATED"
    READY       = "READY"
    STARTING    = "STARTING"
    RUNNING     = "RUNNING"
    LAW         = "LAW"
    QUESTIONS   = "QUESTIONS"
    REVIEW      = "REVIEW"
    SUMMARY     = "SUMMARY"
    AUDIO       = "AUDIO"
    BREAK       = "BREAK"
    ASSESSING   = "ASSESSING"
    ADAPTING    = "ADAPTING"
    COMPLETED   = "COMPLETED"
    INTERRUPTED = "INTERRUPTED"
    FAILED      = "FAILED"
    PAUSED      = "PAUSED"


class StepType(str, Enum):
    LAW        = "LAW"
    QUESTIONS  = "QUESTIONS"
    REVIEW     = "REVIEW"
    FLASHCARDS = "FLASHCARDS"
    SUMMARY    = "SUMMARY"
    AUDIO      = "AUDIO"
    BREAK      = "BREAK"
    ASSESSMENT = "ASSESSMENT"


# Maps StepType → SessionState (active sub-state while step is running)
STEP_TYPE_TO_STATE: dict[StepType, SessionState] = {
    StepType.LAW:        SessionState.LAW,
    StepType.QUESTIONS:  SessionState.QUESTIONS,
    StepType.REVIEW:     SessionState.REVIEW,
    StepType.FLASHCARDS: SessionState.REVIEW,
    StepType.SUMMARY:    SessionState.SUMMARY,
    StepType.AUDIO:      SessionState.AUDIO,
    StepType.BREAK:      SessionState.BREAK,
    StepType.ASSESSMENT: SessionState.ASSESSING,
}


class ObjectiveType(str, Enum):
    MASTER_ARTICLE      = "MASTER_ARTICLE"
    REACH_MASTERY       = "REACH_MASTERY"
    ELIMINATE_CONFUSION = "ELIMINATE_CONFUSION"
    REDUCE_BACKLOG      = "REDUCE_BACKLOG"
    INCREASE_RETENTION  = "INCREASE_RETENTION"
    IMPROVE_CONFIDENCE  = "IMPROVE_CONFIDENCE"
    COMPLETE_MISSION    = "COMPLETE_MISSION"
    REDUCE_ERRORS       = "REDUCE_ERRORS"


class AdaptationTrigger(str, Enum):
    CONSECUTIVE_MISTAKES = "CONSECUTIVE_MISTAKES"
    HIGH_PERFORMANCE     = "HIGH_PERFORMANCE"
    LOW_CONFIDENCE       = "LOW_CONFIDENCE"
    FAST_ANSWERING       = "FAST_ANSWERING"
    FATIGUE_DETECTED     = "FATIGUE_DETECTED"
    CONCEPT_CONFUSION    = "CONCEPT_CONFUSION"
    LOW_RETENTION        = "LOW_RETENTION"
    SESSION_TOO_LONG     = "SESSION_TOO_LONG"
    OBJECTIVE_COMPLETED  = "OBJECTIVE_COMPLETED"
    TIME_PRESSURE        = "TIME_PRESSURE"


class AdaptationAction(str, Enum):
    SWITCH_TO_LAW         = "SWITCH_TO_LAW"
    SWITCH_TO_REVIEW      = "SWITCH_TO_REVIEW"
    SWITCH_TO_QUESTIONS   = "SWITCH_TO_QUESTIONS"
    INSERT_BREAK          = "INSERT_BREAK"
    INCREASE_DIFFICULTY   = "INCREASE_DIFFICULTY"
    DECREASE_DIFFICULTY   = "DECREASE_DIFFICULTY"
    REQUEST_ERROR_TREATMENT = "REQUEST_ERROR_TREATMENT"
    ADVANCE_OBJECTIVE     = "ADVANCE_OBJECTIVE"
    COMPLETE_SESSION      = "COMPLETE_SESSION"


class FatigueLevel(str, Enum):
    FRESH     = "FRESH"
    MILD      = "MILD"
    MODERATE  = "MODERATE"
    HIGH      = "HIGH"
    EXHAUSTED = "EXHAUSTED"


class SessionEventType(str, Enum):
    SESSION_STARTED     = "SESSION_STARTED"
    SESSION_PAUSED      = "SESSION_PAUSED"
    SESSION_RESUMED     = "SESSION_RESUMED"
    SESSION_COMPLETED   = "SESSION_COMPLETED"
    SESSION_INTERRUPTED = "SESSION_INTERRUPTED"
    STEP_STARTED        = "STEP_STARTED"
    STEP_COMPLETED      = "STEP_COMPLETED"
    QUESTION_ANSWERED   = "QUESTION_ANSWERED"
    ARTICLE_READ        = "ARTICLE_READ"
    REVIEW_COMPLETED    = "REVIEW_COMPLETED"
    OBJECTIVE_REACHED   = "OBJECTIVE_REACHED"
    BREAK_STARTED       = "BREAK_STARTED"
    BREAK_FINISHED      = "BREAK_FINISHED"
    ADAPTATION_TRIGGERED = "ADAPTATION_TRIGGERED"
    MISSION_COMPLETED   = "MISSION_COMPLETED"
    FATIGUE_WARNING     = "FATIGUE_WARNING"
