"""External study resources curated by topic for PMGO exam preparation.

Each resource links to a verified external URL (YouTube, government PDFs,
blog articles) mapped to a subject slug. Shown in the frontend as
supplementary material alongside questions, lei seca and audio lessons.
"""

EXTERNAL_RESOURCES: list[dict] = [
    # ── Legislação Institucional PM-GO ──────────────────────────────
    {
        "subject_slug": "legislacao-institucional-pm",
        "title": "Regulamento Disciplinar PM-GO — Decreto 2.639/1986",
        "url": "https://legisla.casacivil.go.gov.br/api/v2/pesquisa/legislacoes/65776/pdf",
        "resource_type": "pdf",
        "source": "Legisla Goiás (gov)",
        "reason": "Lei seca original artigo por artigo; base histórica do CEDIME",
    },
    {
        "subject_slug": "legislacao-institucional-pm",
        "title": "CEDIME — Lei 19.969/2018 (Código Ética e Disciplina Militares GO)",
        "url": "https://legisla.casacivil.go.gov.br/api/v2/pesquisa/legislacoes/99843/pdf",
        "resource_type": "pdf",
        "source": "Legisla Goiás (gov)",
        "reason": "Norma disciplinar vigente; substituiu o decreto e é o que cai em prova atual",
    },
    {
        "subject_slug": "legislacao-institucional-pm",
        "title": "PMGO Explica: Transgressões Disciplinares do Militar Estadual",
        "url": "https://goias.gov.br/policiamilitar/pmgo-explica-transgressoes-disciplinares-do-militar-estadual/",
        "resource_type": "article",
        "source": "Site oficial PMGO",
        "reason": "Fonte primária institucional explicando classificação das transgressões do CEDIME",
    },
    {
        "subject_slug": "legislacao-institucional-pm",
        "title": "Organização Básica PM-GO (DSpace institucional)",
        "url": "https://dspace.pm.go.gov.br/server/api/core/bitstreams/5584d518-b562-4d5d-b90f-7e4b033795a9/content",
        "resource_type": "pdf",
        "source": "PMGO DSpace",
        "reason": "Estrutura organizacional oficial da corporação",
    },
    {
        "subject_slug": "legislacao-institucional-pm",
        "title": "Correção da Prova Soldado PMGO AOCP 2022",
        "url": "https://www.youtube.com/watch?v=Vc7ymM6Wf3A",
        "resource_type": "video",
        "source": "YouTube",
        "reason": "Como AOCP formulou questões de legislação PM-GO na última prova",
    },
    # ── Direito Penal Militar ───────────────────────────────────────
    {
        "subject_slug": "direito-penal-militar",
        "title": "Saber Direito — Direito Penal Militar Aula 1 (TV Justiça)",
        "url": "https://www.youtube.com/watch?v=hBlhM84LCss",
        "resource_type": "video",
        "source": "YouTube",
        "reason": "Série do prof. Cícero Robson Coimbra Neves cobrindo CPM artigo por artigo",
    },
    {
        "subject_slug": "direito-penal-militar",
        "title": "Playlist CPM completa",
        "url": "https://www.youtube.com/playlist?list=PL8N0g0H3P2ExzSQ6PKfzMjCkYoD-eEIy4",
        "resource_type": "video",
        "source": "YouTube",
        "reason": "Playlist estruturada por capítulo do CPM",
    },
    {
        "subject_slug": "direito-penal-militar",
        "title": "Crimes contra Autoridade ou Disciplina Militar — Prof. Muniz PMCE2025",
        "url": "https://www.youtube.com/watch?v=7J9ST8srHSs",
        "resource_type": "video",
        "source": "YouTube",
        "reason": "Crimes militares próprios mais cobrados em concursos PM (2025)",
    },
    {
        "subject_slug": "direito-penal-militar",
        "title": "CPM 2ª Edição atualizada — STM",
        "url": "https://dspace.stm.jus.br/bitstream/handle/123456789/90146/Codigo_Penal_Militar_portalSTM_2%20edi%C3%A7%C3%A3o.pdf",
        "resource_type": "pdf",
        "source": "STM (gov)",
        "reason": "Texto oficial atualizado do CPM para leitura artigo por artigo",
    },
    # ── Direito Processual Penal Militar ────────────────────────────
    {
        "subject_slug": "direito-processual-penal-militar",
        "title": "DPPM — IPM Arts. 9 ao 28 (Prof. Pedro Sillas)",
        "url": "https://www.youtube.com/watch?v=3-e14IA9Kto",
        "resource_type": "video",
        "source": "YouTube",
        "reason": "Aula específica sobre IPM, instituto mais cobrado do CPPM",
    },
    {
        "subject_slug": "direito-processual-penal-militar",
        "title": "Playlist CPPM em áudio — Decreto-lei 1.002/1969",
        "url": "https://www.youtube.com/playlist?list=PL64hzxlE6uurO4ZmbEwBjLEGg4U8QuFEL",
        "resource_type": "video",
        "source": "YouTube",
        "reason": "Lei seca do CPPM lida em sequência; revisão auditiva",
    },
    {
        "subject_slug": "direito-processual-penal-militar",
        "title": "CPPM oficial — STM",
        "url": "https://dspace.stm.jus.br/bitstream/handle/123456789/167/07%20-%20C%C3%B3digo%20de%20Processo%20Penal%20Militar.pdf",
        "resource_type": "pdf",
        "source": "STM (gov)",
        "reason": "Texto oficial atualizado do CPPM",
    },
    {
        "subject_slug": "direito-processual-penal-militar",
        "title": "O IPM no Âmbito das Polícias Militares — JusMilitaris",
        "url": "https://jusmilitaris.com.br/sistema/arquivos/doutrinas/oipmnoambito.pdf",
        "resource_type": "pdf",
        "source": "JusMilitaris",
        "reason": "Doutrina especializada sobre IPM nas PM estaduais",
    },
    # ── Realidade de Goiás ──────────────────────────────────────────
    {
        "subject_slug": "realidade-goias",
        "title": "História e Geografia de Goiás — Prof. Chagas Sousa (2024/2025)",
        "url": "https://www.youtube.com/watch?v=bcDab5O6phA",
        "resource_type": "video",
        "source": "YouTube",
        "reason": "Aula atualizada com temas cobrados em 2024/2025 para concursos GO",
    },
    {
        "subject_slug": "realidade-goias",
        "title": "Geo-história de Goiás — Maratona SEFAZ/ALEGO 2025",
        "url": "https://www.youtube.com/watch?v=_nOyRgq_MKY",
        "resource_type": "video",
        "source": "YouTube",
        "reason": "Concursos estaduais GO 2025, mapa mental de história e geografia",
    },
    {
        "subject_slug": "realidade-goias",
        "title": "História e Geografia de Goiás — Resumo para concursos",
        "url": "https://www.youtube.com/watch?v=0mpBiBQ91B0",
        "resource_type": "video",
        "source": "YouTube",
        "reason": "Resumo compacto para fixação rápida",
    },
    {
        "subject_slug": "realidade-goias",
        "title": "Formação Econômica de Goiás — Concurso PPGO",
        "url": "https://www.youtube.com/watch?v=omJH50ugCFE",
        "resource_type": "video",
        "source": "YouTube",
        "reason": "Dimensão econômica frequentemente esquecida; cobrada em concursos GO",
    },
    {
        "subject_slug": "realidade-goias",
        "title": "Aula Realidade de Goiás — Gran Cursos (ALEGO 2025)",
        "url": "https://blog.grancursosonline.com.br/concurso-alego-aula-realidade-de-goias-2025/",
        "resource_type": "article",
        "source": "Gran Cursos Blog",
        "reason": "Resumo escrito com tópicos mapeados para concurso estadual GO",
    },
    # ── Criminologia ────────────────────────────────────────────────
    {
        "subject_slug": "criminologia",
        "title": "Noções de Criminologia — Questões CEBRASPE (Laécio Carneiro, PMDF)",
        "url": "https://www.youtube.com/watch?v=hpXciWz9Dxc",
        "resource_type": "video",
        "source": "YouTube",
        "reason": "Questões comentadas com foco em PM; CEBRASPE e AOCP estilo parecido",
    },
    {
        "subject_slug": "criminologia",
        "title": "Noções de Criminologia em Questões — PMCE",
        "url": "https://www.youtube.com/watch?v=KUXs_7kh_BY",
        "resource_type": "video",
        "source": "YouTube",
        "reason": "Resolve questões típicas de PM explicando escolas criminológicas",
    },
    {
        "subject_slug": "criminologia",
        "title": "Criminologia na PCPE — Parte 1",
        "url": "https://www.youtube.com/watch?v=qBzJQTuZx_g",
        "resource_type": "video",
        "source": "YouTube",
        "reason": "Escolas clássica e positiva para concursos policiais",
    },
    {
        "subject_slug": "criminologia",
        "title": "Escolas Criminológicas — Dedicação Delta",
        "url": "https://blog.dedicacaodelta.com.br/escolas-criminologicas/",
        "resource_type": "article",
        "source": "Blog Dedicação Delta",
        "reason": "Quadro comparativo das escolas; bom para fixar diferenças",
    },
    # ── Medicina Legal ──────────────────────────────────────────────
    {
        "subject_slug": "medicina-legal",
        "title": "Morte e Tanatognose — Medicina Legal (Aula Gratuita)",
        "url": "https://www.youtube.com/watch?v=SM8xrAk67oQ",
        "resource_type": "video",
        "source": "YouTube",
        "reason": "Tanatologia: tema mais cobrado de Med Legal em concursos PM",
    },
    {
        "subject_slug": "medicina-legal",
        "title": "Medicina Legal 2023/2024 — Tanatologia Forense",
        "url": "https://www.youtube.com/watch?v=P7IvsgDi72w",
        "resource_type": "video",
        "source": "YouTube",
        "reason": "Cronotanatognose e diagnóstico de morte, frequente em provas PM",
    },
    {
        "subject_slug": "medicina-legal",
        "title": "Med Legal Aula 15 — Tanatologia IV + Sexologia Forense I",
        "url": "https://www.youtube.com/watch?v=NrIL8uVU9p0",
        "resource_type": "video",
        "source": "YouTube",
        "reason": "Dois temas num bloco: fim de tanatologia + início de sexologia forense",
    },
    {
        "subject_slug": "medicina-legal",
        "title": "Med Legal Prof. Janiel Santana — Concurso Polícia Civil 3.0",
        "url": "https://www.youtube.com/watch?v=1Tczq7wJXS4",
        "resource_type": "video",
        "source": "YouTube",
        "reason": "Abordagem sistemática por tópicos para concursos policiais",
    },
    {
        "subject_slug": "medicina-legal",
        "title": "Playlist Medicina Legal — Aulas completas",
        "url": "https://www.youtube.com/playlist?list=PL1XAwazhY7lEgCnd_siqnpKjHWADgJZfN",
        "resource_type": "video",
        "source": "YouTube",
        "reason": "Série estruturada cobrindo todos capítulos de Med Legal",
    },
]
