"""
Seeder — usa produtos curados quando banco está vazio.
Não usa scrapers externos que trazem produtos irrelevantes.
"""
import uuid, json, logging
from typing import List, Dict

logger = logging.getLogger(__name__)

CURATED_PRODUCTS: List[Dict] = [
    {"title":"Pistola de Massagem Muscular Portátil 6 Velocidades","category":"Saúde","platform":"aliexpress","price_usd":12.99,"cost_brl":97.0,"freight_brl":19.0,"tax_brl":23.2,"total_cost_brl":139.2,"suggested_sell_price":189.9,"markup":4.2,"orders_count":85420,"rating":4.8,"br_status":"Pouco Vendido","score":87,"opportunity":70,"saturation_pct":25,"images":["https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400"],"image_url":"https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400","product_url":"https://www.aliexpress.com/item/1005003","tags":["massagem","esporte","recuperação"],"is_new":False,"is_viral":True,"highlight":True,"growth":"+34%","delivery_days":"15-25","targeting_suggestion":["Fisioterapia","Dor nas costas","Bem-estar","Saúde e fitness","Yoga"],"copy_suggestion":"🔥 Acabar com a dor SEM sair de casa! Pistola de Massagem Muscular com tecnologia profissional ao seu alcance. Frete grátis + 30 dias de garantia."},
    {"title":"Escova Alisadora Rotativa de Cerâmica para Cabelo","category":"Beleza","platform":"aliexpress","price_usd":8.50,"cost_brl":63.5,"freight_brl":19.0,"tax_brl":16.5,"total_cost_brl":99.0,"suggested_sell_price":149.9,"markup":5.1,"orders_count":124000,"rating":4.7,"br_status":"Pouco Vendido","score":92,"opportunity":75,"saturation_pct":20,"images":["https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=400"],"image_url":"https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=400","product_url":"https://www.aliexpress.com/item/1005004","tags":["cabelo","beleza","alisamento"],"is_new":False,"is_viral":True,"highlight":True,"growth":"+28%","delivery_days":"14-22","targeting_suggestion":["Cuidados com a pele","Maquiagem","Beleza feminina","Skincare","Autocuidado"],"copy_suggestion":"✨ O segredo das influencers! Escova Alisadora Rotativa de Cerâmica que as profissionais usam. Resultados em 7 dias ou devolvemos seu dinheiro."},
    {"title":"Máscara LED Facial 7 Cores Rejuvenescimento","category":"Beleza","platform":"aliexpress","price_usd":11.20,"cost_brl":83.6,"freight_brl":19.0,"tax_brl":20.5,"total_cost_brl":123.1,"suggested_sell_price":197.9,"markup":4.8,"orders_count":67000,"rating":4.6,"br_status":"Não Vendido","score":89,"opportunity":90,"saturation_pct":8,"images":["https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=400"],"image_url":"https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=400","product_url":"https://www.aliexpress.com/item/1005005","tags":["led","facial","skincare"],"is_new":True,"is_viral":False,"highlight":True,"growth":"+67%","delivery_days":"18-28","targeting_suggestion":["Cuidados com a pele","Maquiagem","Beleza feminina","Skincare","Autocuidado"],"copy_suggestion":"✨ Máscara LED Facial 7 Cores para Rejuvenescimento da Pele. Resultados visíveis em 7 dias ou devolvemos seu dinheiro."},
    {"title":"Brinquedo Automático para Gatos com Pena","category":"Pet","platform":"aliexpress","price_usd":5.30,"cost_brl":39.6,"freight_brl":15.0,"tax_brl":10.9,"total_cost_brl":65.5,"suggested_sell_price":97.9,"markup":5.5,"orders_count":98000,"rating":4.9,"br_status":"Não Vendido","score":94,"opportunity":92,"saturation_pct":5,"images":["https://images.unsplash.com/photo-1548247416-ec66f4900b2e?w=400"],"image_url":"https://images.unsplash.com/photo-1548247416-ec66f4900b2e?w=400","product_url":"https://www.aliexpress.com/item/1005006","tags":["gato","pet","brinquedo"],"is_new":True,"is_viral":True,"highlight":True,"growth":"+89%","delivery_days":"12-20","targeting_suggestion":["Donos de gatos","Donos de cachorros","Produtos para pets","Animais de estimação","Pet shop"],"copy_suggestion":"🐾 Brinquedo Automático para Gatos aprovado por veterinários! Mais de 50.000 tutores já adotaram."},
    {"title":"Mini Mixer Portátil USB para Shakes e Sucos","category":"Casa","platform":"aliexpress","price_usd":7.80,"cost_brl":58.2,"freight_brl":16.0,"tax_brl":14.8,"total_cost_brl":89.0,"suggested_sell_price":134.9,"markup":4.3,"orders_count":210000,"rating":4.7,"br_status":"Pouco Vendido","score":85,"opportunity":65,"saturation_pct":30,"images":["https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=400"],"image_url":"https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=400","product_url":"https://www.aliexpress.com/item/1005007","tags":["mixer","cozinha","portátil"],"is_new":False,"is_viral":False,"highlight":False,"growth":"+15%","delivery_days":"14-22","targeting_suggestion":["Decoração de interiores","Organização doméstica","Casa inteligente","Cozinha gourmet","DIY"],"copy_suggestion":"🏠 Mini Mixer Portátil USB — a solução que vai transformar sua rotina! Mais de 100.000 vendidos no mundo."},
    {"title":"Suporte Magnético Veicular para Celular 360 Graus","category":"Eletrônicos","platform":"aliexpress","price_usd":3.50,"cost_brl":26.1,"freight_brl":12.0,"tax_brl":7.6,"total_cost_brl":45.7,"suggested_sell_price":79.9,"markup":6.2,"orders_count":320000,"rating":4.8,"br_status":"Já Vendido","score":78,"opportunity":30,"saturation_pct":70,"images":["https://images.unsplash.com/photo-1586244759912-5ce7a93a7e08?w=400"],"image_url":"https://images.unsplash.com/photo-1586244759912-5ce7a93a7e08?w=400","product_url":"https://www.aliexpress.com/item/1005008","tags":["suporte","carro","celular"],"is_new":False,"is_viral":False,"highlight":False,"growth":"+5%","delivery_days":"10-18","targeting_suggestion":["Tecnologia","Gadgets","Smartphone","Acessórios tech","Inovação"],"copy_suggestion":"📱 Suporte Magnético Veicular para Celular com tecnologia de ponta. Estoque limitado!"},
    {"title":"Massageador Elétrico para Joelho com Aquecimento","category":"Saúde","platform":"aliexpress","price_usd":15.00,"cost_brl":112.0,"freight_brl":22.0,"tax_brl":26.8,"total_cost_brl":160.8,"suggested_sell_price":249.9,"markup":3.8,"orders_count":48000,"rating":4.6,"br_status":"Não Vendido","score":86,"opportunity":88,"saturation_pct":7,"images":["https://images.unsplash.com/photo-1559757175-5700dde675bc?w=400"],"image_url":"https://images.unsplash.com/photo-1559757175-5700dde675bc?w=400","product_url":"https://www.aliexpress.com/item/1005009","tags":["joelho","massagem","dor"],"is_new":True,"is_viral":False,"highlight":True,"growth":"+45%","delivery_days":"18-28","targeting_suggestion":["Fisioterapia","Dor nas costas","Bem-estar","Saúde e fitness","Yoga"],"copy_suggestion":"🔥 Massageador Elétrico para Joelho com aquecimento terapêutico. Alívio em 15 minutos!"},
    {"title":"Corretor de Postura Ajustável Invisível","category":"Saúde","platform":"aliexpress","price_usd":6.20,"cost_brl":46.3,"freight_brl":14.0,"tax_brl":12.1,"total_cost_brl":72.4,"suggested_sell_price":119.9,"markup":5.0,"orders_count":185000,"rating":4.5,"br_status":"Pouco Vendido","score":83,"opportunity":60,"saturation_pct":35,"images":["https://images.unsplash.com/photo-1587645483890-21a12a8fc1fc?w=400"],"image_url":"https://images.unsplash.com/photo-1587645483890-21a12a8fc1fc?w=400","product_url":"https://www.aliexpress.com/item/1005010","tags":["postura","coluna","ergonômico"],"is_new":False,"is_viral":False,"highlight":False,"growth":"+12%","delivery_days":"14-22","targeting_suggestion":["Fisioterapia","Dor nas costas","Bem-estar","Saúde e fitness","Yoga"],"copy_suggestion":"🔥 Corretor de Postura Ajustável Invisível — fim da dor nas costas sem sair de casa!"},
    {"title":"Garrafa de Água Portátil para Pets com Filtro","category":"Pet","platform":"aliexpress","price_usd":4.80,"cost_brl":35.8,"freight_brl":13.0,"tax_brl":9.8,"total_cost_brl":58.6,"suggested_sell_price":97.9,"markup":5.8,"orders_count":115000,"rating":4.9,"br_status":"Não Vendido","score":91,"opportunity":90,"saturation_pct":6,"images":["https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400"],"image_url":"https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400","product_url":"https://www.aliexpress.com/item/1005011","tags":["pet","água","portátil"],"is_new":True,"is_viral":True,"highlight":True,"growth":"+78%","delivery_days":"12-20","targeting_suggestion":["Donos de gatos","Donos de cachorros","Produtos para pets","Animais de estimação","Pet shop"],"copy_suggestion":"🐾 Garrafa de Água Portátil para Pets — aprovado por veterinários!"},
    {"title":"Massageador Ocular com Vibração e Aquecimento","category":"Saúde","platform":"aliexpress","price_usd":13.50,"cost_brl":100.8,"freight_brl":20.0,"tax_brl":24.2,"total_cost_brl":145.0,"suggested_sell_price":229.9,"markup":4.5,"orders_count":72000,"rating":4.7,"br_status":"Não Vendido","score":88,"opportunity":88,"saturation_pct":8,"images":["https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=400"],"image_url":"https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=400","product_url":"https://www.aliexpress.com/item/1005012","tags":["olhos","massagem","relaxamento"],"is_new":True,"is_viral":False,"highlight":True,"growth":"+56%","delivery_days":"16-26","targeting_suggestion":["Fisioterapia","Dor nas costas","Bem-estar","Saúde e fitness","Yoga"],"copy_suggestion":"🔥 Massageador Ocular com Vibração e Aquecimento — relaxamento instantâneo para seus olhos!"},
    {"title":"Massageador de Couro Cabeludo Elétrico","category":"Beleza","platform":"aliexpress","price_usd":9.90,"cost_brl":73.9,"freight_brl":17.0,"tax_brl":18.2,"total_cost_brl":109.1,"suggested_sell_price":169.9,"markup":4.6,"orders_count":89000,"rating":4.8,"br_status":"Pouco Vendido","score":86,"opportunity":68,"saturation_pct":22,"images":["https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=400"],"image_url":"https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=400","product_url":"https://www.aliexpress.com/item/1005013","tags":["cabelo","couro cabeludo","massagem"],"is_new":False,"is_viral":True,"highlight":False,"growth":"+23%","delivery_days":"14-22","targeting_suggestion":["Cuidados com a pele","Maquiagem","Beleza feminina","Skincare","Autocuidado"],"copy_suggestion":"✨ Massageador de Couro Cabeludo Elétrico à Prova D'água — resultados visíveis em 7 dias!"},
    {"title":"Kit Elásticos de Resistência para Musculação","category":"Fitness","platform":"aliexpress","price_usd":5.90,"cost_brl":44.0,"freight_brl":14.0,"tax_brl":11.6,"total_cost_brl":69.6,"suggested_sell_price":109.9,"markup":5.2,"orders_count":156000,"rating":4.6,"br_status":"Pouco Vendido","score":84,"opportunity":62,"saturation_pct":28,"images":["https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400"],"image_url":"https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400","product_url":"https://www.aliexpress.com/item/1005014","tags":["fitness","musculação","elástico"],"is_new":False,"is_viral":False,"highlight":False,"growth":"+18%","delivery_days":"12-20","targeting_suggestion":["Academia","Musculação","Corrida","CrossFit","Vida saudável"],"copy_suggestion":"💪 Kit Elásticos de Resistência — treino em casa com resultado de academia!"},
    {"title":"Rolo de Espuma para Massagem Muscular","category":"Fitness","platform":"aliexpress","price_usd":8.20,"cost_brl":61.2,"freight_brl":18.0,"tax_brl":15.8,"total_cost_brl":95.0,"suggested_sell_price":149.9,"markup":4.7,"orders_count":93000,"rating":4.5,"br_status":"Pouco Vendido","score":81,"opportunity":58,"saturation_pct":32,"images":["https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400"],"image_url":"https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400","product_url":"https://www.aliexpress.com/item/1005015","tags":["fitness","recuperação","massagem"],"is_new":False,"is_viral":False,"highlight":False,"growth":"+9%","delivery_days":"14-22","targeting_suggestion":["Academia","Musculação","Corrida","CrossFit","Vida saudável"],"copy_suggestion":"💪 Rolo de Espuma para Massagem Muscular Pós-Treino — recuperação rápida garantida!"},
    {"title":"Kit Clareamento Dental LED Profissional","category":"Beleza","platform":"aliexpress","price_usd":10.50,"cost_brl":78.4,"freight_brl":17.0,"tax_brl":19.1,"total_cost_brl":114.5,"suggested_sell_price":189.9,"markup":4.9,"orders_count":61000,"rating":4.6,"br_status":"Não Vendido","score":87,"opportunity":85,"saturation_pct":10,"images":["https://images.unsplash.com/photo-1606811841689-23dfddce3e95?w=400"],"image_url":"https://images.unsplash.com/photo-1606811841689-23dfddce3e95?w=400","product_url":"https://www.aliexpress.com/item/1005016","tags":["dentes","clareamento","beleza"],"is_new":True,"is_viral":False,"highlight":True,"growth":"+52%","delivery_days":"16-24","targeting_suggestion":["Cuidados com a pele","Maquiagem","Beleza feminina","Skincare","Autocuidado"],"copy_suggestion":"✨ Kit Clareamento Dental LED — resultado profissional em casa! Visível em 7 dias."},
    {"title":"Luminária LED para Plantas Indoor","category":"Casa","platform":"aliexpress","price_usd":11.80,"cost_brl":88.1,"freight_brl":20.0,"tax_brl":21.6,"total_cost_brl":129.7,"suggested_sell_price":199.9,"markup":4.5,"orders_count":44000,"rating":4.7,"br_status":"Não Vendido","score":85,"opportunity":87,"saturation_pct":9,"images":["https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400"],"image_url":"https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400","product_url":"https://www.aliexpress.com/item/1005017","tags":["plantas","led","jardim"],"is_new":True,"is_viral":False,"highlight":True,"growth":"+61%","delivery_days":"18-26","targeting_suggestion":["Decoração de interiores","Organização doméstica","Casa inteligente","Cozinha gourmet","DIY"],"copy_suggestion":"🏠 Luminária LED para Plantas Indoor — transforme sua casa em um jardim!"},
    {"title":"Aspirador Nasal Elétrico para Bebê","category":"Bebê","platform":"aliexpress","price_usd":9.20,"cost_brl":68.7,"freight_brl":16.0,"tax_brl":16.9,"total_cost_brl":101.6,"suggested_sell_price":159.9,"markup":4.6,"orders_count":78000,"rating":4.8,"br_status":"Não Vendido","score":88,"opportunity":89,"saturation_pct":7,"images":["https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=400"],"image_url":"https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=400","product_url":"https://www.aliexpress.com/item/1005018","tags":["bebê","saúde","nasal"],"is_new":True,"is_viral":False,"highlight":True,"growth":"+43%","delivery_days":"16-24","targeting_suggestion":["Mamães de primeira viagem","Gravidez","Maternidade","Bebês 0-2 anos","Pediatria"],"copy_suggestion":"👶 Aspirador Nasal Elétrico para Bebê 100% seguro, aprovado por pediatras!"},
    {"title":"Espumador de Café Elétrico Mini Recarregável","category":"Casa","platform":"aliexpress","price_usd":4.20,"cost_brl":31.4,"freight_brl":12.0,"tax_brl":8.7,"total_cost_brl":52.1,"suggested_sell_price":84.9,"markup":5.8,"orders_count":230000,"rating":4.7,"br_status":"Pouco Vendido","score":83,"opportunity":60,"saturation_pct":30,"images":["https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400"],"image_url":"https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400","product_url":"https://www.aliexpress.com/item/1005019","tags":["café","cozinha","espuma"],"is_new":False,"is_viral":False,"highlight":False,"growth":"+14%","delivery_days":"12-18","targeting_suggestion":["Decoração de interiores","Organização doméstica","Casa inteligente","Cozinha gourmet","DIY"],"copy_suggestion":"🏠 Espumador de Café Mini Recarregável — seu café gourmet em casa!"},
    {"title":"Meias de Compressão para Corrida e Esporte","category":"Fitness","platform":"aliexpress","price_usd":3.80,"cost_brl":28.4,"freight_brl":11.0,"tax_brl":7.9,"total_cost_brl":47.3,"suggested_sell_price":79.9,"markup":5.9,"orders_count":145000,"rating":4.6,"br_status":"Pouco Vendido","score":82,"opportunity":58,"saturation_pct":32,"images":["https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400"],"image_url":"https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400","product_url":"https://www.aliexpress.com/item/1005020","tags":["meias","corrida","compressão"],"is_new":False,"is_viral":False,"highlight":False,"growth":"+11%","delivery_days":"12-20","targeting_suggestion":["Academia","Musculação","Corrida","CrossFit","Vida saudável"],"copy_suggestion":"💪 Meias de Compressão para Corrida — desempenho e conforto em cada passo!"},
    {"title":"Massageador Anticelulite Elétrico Corporal","category":"Beleza","platform":"aliexpress","price_usd":14.50,"cost_brl":108.2,"freight_brl":21.0,"tax_brl":25.8,"total_cost_brl":155.0,"suggested_sell_price":239.9,"markup":4.3,"orders_count":55000,"rating":4.7,"br_status":"Não Vendido","score":87,"opportunity":86,"saturation_pct":9,"images":["https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=400"],"image_url":"https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=400","product_url":"https://www.aliexpress.com/item/1005021","tags":["celulite","corpo","beleza"],"is_new":True,"is_viral":True,"highlight":True,"growth":"+72%","delivery_days":"17-25","targeting_suggestion":["Cuidados com a pele","Maquiagem","Beleza feminina","Skincare","Autocuidado"],"copy_suggestion":"✨ Massageador Anticelulite Elétrico — resultado real visível em 30 dias!"},
]


async def seed_if_empty(db) -> int:
    try:
        p = await db._p()
        async with p.acquire() as c:
            count = await c.fetchval("SELECT COUNT(*) FROM products")
        if count > 0:
            logger.info(f"Seed ignorado: {count} produtos existentes")
            return 0

        import uuid as _uuid, json as _json
        enriched = []
        for prod in CURATED_PRODUCTS:
            pid = str(_uuid.uuid5(_uuid.NAMESPACE_URL, prod["product_url"]))
            enriched.append({
                **prod,
                "product_id": pid,
                "sources": [],
                "growth": prod.get("growth", "+0%"),
                "supplier_name": "AliExpress",
            })

        await db.upsert_products(enriched)
        logger.info(f"Seed curado: {len(enriched)} produtos inseridos")
        return len(enriched)
    except Exception as e:
        logger.error(f"Seed falhou: {e}")
        return 0
