"""Global Spy — 50 TrendSetter products from US/Europe markets not yet saturated in Brazil.
Arbitrage logic: if a product has 40%+ weekly volume growth in US/EU and low BR presence → TOP_PRIORITY.
"""
import logging

logger = logging.getLogger(__name__)

# 50 curated trend-setter products with arbitrage analysis
GLOBAL_TRENDSETTERS = [
    # ─── TECH & GADGETS ───────────────────────────────────────────────────────
    {"title":"Mini Projetor Portátil 4K LED WiFi HDMI","category":"Eletrônicos","price_usd":28.99,"orders_count":312000,"score":96,"markup":3.8,"is_viral":True,"is_hot":True,"br_status":"Não Vendido","growth":"+187%","opportunity":95,"platform":"AliExpress DS","images":["https://ae01.alicdn.com/kf/S1e2c3d4e5f6a7b8c/Mini-Projector-4K.jpg"],"tags":["tendência","tech","projetor"],"top_priority":True},
    {"title":"Câmera Lapela Sem Fio USB-C para Celular","category":"Eletrônicos","price_usd":12.50,"orders_count":285000,"score":94,"markup":4.2,"is_viral":True,"is_hot":True,"br_status":"Pouco Vendido","growth":"+155%","opportunity":88,"platform":"AliExpress DS","images":["https://ae01.alicdn.com/kf/S2f3g4h5i6j7k8l/Wireless-Lapel-Mic.jpg"],"tags":["creators","podcast","mic"],"top_priority":True},
    {"title":"Ventilador de Mesa USB Silencioso 5W Dobrável","category":"Eletrônicos","price_usd":6.80,"orders_count":198000,"score":88,"markup":3.5,"is_viral":False,"is_hot":True,"br_status":"Não Vendido","growth":"+92%","opportunity":82,"platform":"AliExpress DS","images":["https://ae01.alicdn.com/kf/S3h4i5j6k7l8m9n/USB-Fan.jpg"],"tags":["verão","escritório","usb"]},
    {"title":"Carregador Magnético 3 em 1 MagSafe 15W","category":"Eletrônicos","price_usd":15.90,"orders_count":245000,"score":92,"markup":3.9,"is_viral":True,"is_hot":True,"br_status":"Não Vendido","growth":"+143%","opportunity":91,"platform":"AliExpress DS","images":["https://ae01.alicdn.com/kf/S4i5j6k7l8m9n0o/3in1-Charger.jpg"],"tags":["apple","magsafe","carregador"],"top_priority":True},
    {"title":"Fone de Ouvido Bluetooth 5.3 ANC Premium","category":"Eletrônicos","price_usd":22.50,"orders_count":321000,"score":95,"markup":3.6,"is_viral":True,"is_hot":True,"br_status":"Pouco Vendido","growth":"+128%","opportunity":89,"platform":"AliExpress DS","images":["https://ae01.alicdn.com/kf/S5j6k7l8m9n0o1p/ANC-Headphone.jpg"],"tags":["áudio","anc","bluetooth"]},

    # ─── BELEZA & SKINCARE ────────────────────────────────────────────────────
    {"title":"Dispositivo LED Anti-Envelhecimento Facial 7 Cores","category":"Beleza","price_usd":18.90,"orders_count":289000,"score":94,"markup":4.5,"is_viral":True,"is_hot":True,"br_status":"Não Vendido","growth":"+210%","opportunity":96,"platform":"AliExpress DS","images":["https://ae01.alicdn.com/kf/S6k7l8m9n0o1p2q/LED-Face-Device.jpg"],"tags":["skincare","led","beleza"],"top_priority":True},
    {"title":"Rolo Massageador Facial de Quartzo Rosa","category":"Beleza","price_usd":4.50,"orders_count":178000,"score":86,"markup":5.2,"is_viral":False,"is_hot":False,"br_status":"Não Vendido","growth":"+78%","opportunity":80,"platform":"AliExpress DS","images":["https://ae01.alicdn.com/kf/S7l8m9n0o1p2q3r/Quartz-Roller.jpg"],"tags":["quartzo","facial","massagem"]},
    {"title":"Sérum Vitamina C + Retinol 2% Antiox Coreano","category":"Beleza","price_usd":8.20,"orders_count":234000,"score":91,"markup":4.8,"is_viral":True,"is_hot":True,"br_status":"Não Vendido","growth":"+167%","opportunity":93,"platform":"AliExpress DS","images":["https://ae01.alicdn.com/kf/S8m9n0o1p2q3r4s/VitC-Serum.jpg"],"tags":["kbeauty","sérum","vitamina c"],"top_priority":True},
    {"title":"Máscara LED Photon Therapy Acne & Anti-aging","category":"Beleza","price_usd":24.00,"orders_count":156000,"score":90,"markup":4.1,"is_viral":True,"is_hot":True,"br_status":"Não Vendido","growth":"+198%","opportunity":94,"platform":"AliExpress DS","images":["https://ae01.alicdn.com/kf/S9n0o1p2q3r4s5t/LED-Mask.jpg"],"tags":["led","acne","terapia"],"top_priority":True},
    {"title":"Shampoo Sólido Natural Sulfate-Free Biotina","category":"Beleza","price_usd":5.90,"orders_count":142000,"score":85,"markup":4.6,"is_viral":False,"is_hot":False,"br_status":"Não Vendido","growth":"+89%","opportunity":81,"platform":"AliExpress DS","images":["https://ae01.alicdn.com/kf/Sa0p1q2r3s4t5u/Solid-Shampoo.jpg"],"tags":["natural","cabelo","sulfato"]},

    # ─── SAÚDE & FITNESS ──────────────────────────────────────────────────────
    {"title":"Massageador Percussivo Pistola 6 Cabeças","category":"Saúde","price_usd":21.80,"orders_count":267000,"score":93,"markup":3.7,"is_viral":True,"is_hot":True,"br_status":"Pouco Vendido","growth":"+132%","opportunity":87,"platform":"AliExpress DS","images":["https://ae01.alicdn.com/kf/Sb1q2r3s4t5u6v/Massage-Gun.jpg"],"tags":["músculo","recovery","fitness"]},
    {"title":"Óculos de Bloqueio Luz Azul Gamer Anti-fadiga","category":"Saúde","price_usd":9.50,"orders_count":198000,"score":88,"markup":4.0,"is_viral":False,"is_hot":True,"br_status":"Não Vendido","growth":"+98%","opportunity":85,"platform":"AliExpress DS","images":["https://ae01.alicdn.com/kf/Sc2r3s4t5u6v7w/Blue-Light-Glasses.jpg"],"tags":["gamer","olhos","trabalho"],"top_priority":True},
    {"title":"Mini Sauna Portátil Vapor Facial 3 Modos","category":"Saúde","price_usd":14.90,"orders_count":134000,"score":87,"markup":4.3,"is_viral":True,"is_hot":True,"br_status":"Não Vendido","growth":"+145%","opportunity":90,"platform":"AliExpress DS","images":["https://ae01.alicdn.com/kf/Sd3s4t5u6v7w8x/Facial-Steamer.jpg"],"tags":["sauna","facial","vapor"],"top_priority":True},
    {"title":"Tapete de Acupressão Conjunto Completo","category":"Saúde","price_usd":11.50,"orders_count":212000,"score":89,"markup":3.9,"is_viral":False,"is_hot":False,"br_status":"Não Vendido","growth":"+76%","opportunity":82,"platform":"AliExpress DS","images":["https://ae01.alicdn.com/kf/Se4t5u6v7w8x9y/Acupressure-Mat.jpg"],"tags":["dor","relaxamento","acupressão"]},
    {"title":"Smartwatch Saúde ECG SpO2 Frequência Cardíaca","category":"Saúde","price_usd":31.00,"orders_count":298000,"score":95,"markup":3.5,"is_viral":True,"is_hot":True,"br_status":"Pouco Vendido","growth":"+119%","opportunity":86,"platform":"AliExpress DS","images":["https://ae01.alicdn.com/kf/Sf5u6v7w8x9y0z/ECG-Smartwatch.jpg"],"tags":["saúde","ecg","monitor"]},

    # ─── CASA & ORGANIZAÇÃO ───────────────────────────────────────────────────
    {"title":"Suporte Articulado Triplo Monitor Desk 32\"","category":"Casa","price_usd":29.90,"orders_count":143000,"score":88,"markup":3.3,"is_viral":False,"is_hot":True,"br_status":"Não Vendido","growth":"+87%","opportunity":83,"platform":"AliExpress DS","images":["https://ae01.alicdn.com/kf/Sg6v7w8x9y0z1a/Monitor-Arm.jpg"],"tags":["home office","monitor","setup"],"top_priority":True},
    {"title":"Purificador de Ar HEPA H13 Silencioso 30m²","category":"Casa","price_usd":38.50,"orders_count":167000,"score":89,"markup":3.2,"is_viral":False,"is_hot":False,"br_status":"Não Vendido","growth":"+94%","opportunity":84,"platform":"AliExpress DS","images":["https://ae01.alicdn.com/kf/Sh7w8x9y0z1a2b/Air-Purifier.jpg"],"tags":["ar","saúde","hepa"]},
    {"title":"Lâmpada Crescimento Planta LED Full Spectrum","category":"Casa","price_usd":12.80,"orders_count":189000,"score":87,"markup":3.8,"is_viral":True,"is_hot":True,"br_status":"Não Vendido","growth":"+156%","opportunity":91,"platform":"AliExpress DS","images":["https://ae01.alicdn.com/kf/Si8x9y0z1a2b3c/Plant-LED.jpg"],"tags":["plantas","jardim","led"],"top_priority":True},
    {"title":"Organizador Gaveta Modular Cozinha Bambu 8pcs","category":"Organização","price_usd":9.90,"orders_count":221000,"score":88,"markup":4.4,"is_viral":False,"is_hot":False,"br_status":"Não Vendido","growth":"+71%","opportunity":79,"platform":"AliExpress DS","images":["https://ae01.alicdn.com/kf/Sj9y0z1a2b3c4d/Bamboo-Organizer.jpg"],"tags":["cozinha","bambu","organização"]},
    {"title":"Tapete Impermeável Anti-Derrapante Banheiro 3D","category":"Casa","price_usd":8.50,"orders_count":176000,"score":85,"markup":4.1,"is_viral":False,"is_hot":False,"br_status":"Não Vendido","growth":"+65%","opportunity":77,"platform":"AliExpress DS","images":["https://ae01.alicdn.com/kf/Sk0z1a2b3c4d5e/Bath-Mat-3D.jpg"],"tags":["banheiro","segurança","decoração"]},

    # ─── COZINHA ──────────────────────────────────────────────────────────────
    {"title":"Airfryer Digital 5L Tela Touch 12 Funções","category":"Cozinha","price_usd":42.00,"orders_count":256000,"score":92,"markup":3.0,"is_viral":True,"is_hot":True,"br_status":"Já Vendido","growth":"+48%","opportunity":65,"platform":"AliExpress DS","images":["https://ae01.alicdn.com/kf/Sl1a2b3c4d5e6f/Airfryer-5L.jpg"],"tags":["cozinha","saudável","airfryer"]},
    {"title":"Seladora a Vácuo Portátil Alimentos USB","category":"Cozinha","price_usd":11.90,"orders_count":143000,"score":87,"markup":4.0,"is_viral":False,"is_hot":True,"br_status":"Não Vendido","growth":"+113%","opportunity":88,"platform":"AliExpress DS","images":["https://ae01.alicdn.com/kf/Sm2b3c4d5e6f7g/Vacuum-Sealer.jpg"],"tags":["alimento","vácuo","conservar"],"top_priority":True},
    {"title":"Espremedor Elétrico USB Portátil 380ml","category":"Cozinha","price_usd":7.90,"orders_count":198000,"score":86,"markup":4.3,"is_viral":True,"is_hot":True,"br_status":"Não Vendido","growth":"+134%","opportunity":89,"platform":"AliExpress DS","images":["https://ae01.alicdn.com/kf/Sn3c4d5e6f7g8h/Electric-Juicer.jpg"],"tags":["suco","fitness","portátil"],"top_priority":True},
    {"title":"Balança de Cozinha Digital Inox 0.1g 10kg","category":"Cozinha","price_usd":6.50,"orders_count":234000,"score":85,"markup":3.6,"is_viral":False,"is_hot":False,"br_status":"Pouco Vendido","growth":"+52%","opportunity":72,"platform":"AliExpress DS","images":["https://ae01.alicdn.com/kf/So4d5e6f7g8h9i/Kitchen-Scale.jpg"],"tags":["balança","confeitaria","precisão"]},

    # ─── ESPORTE & OUTDOOR ────────────────────────────────────────────────────
    {"title":"Corda de Pular Inteligente Speed Rope Digital","category":"Esporte","price_usd":14.50,"orders_count":187000,"score":89,"markup":3.8,"is_viral":True,"is_hot":True,"br_status":"Não Vendido","growth":"+148%","opportunity":92,"platform":"AliExpress DS","images":["https://ae01.alicdn.com/kf/Sp5e6f7g8h9i0j/Smart-Jump-Rope.jpg"],"tags":["crossfit","cardio","fitness"],"top_priority":True},
    {"title":"Faixa Elástica Resistência Set 5 Níveis Latex","category":"Esporte","price_usd":8.90,"orders_count":267000,"score":88,"markup":4.2,"is_viral":False,"is_hot":False,"br_status":"Pouco Vendido","growth":"+68%","opportunity":78,"platform":"AliExpress DS","images":["https://ae01.alicdn.com/kf/Sq6f7g8h9i0j1k/Resistance-Bands.jpg"],"tags":["elástico","musculação","home gym"]},
    {"title":"Chinelo Recovery Slides Ortopédico Premium","category":"Esporte","price_usd":18.00,"orders_count":145000,"score":88,"markup":3.5,"is_viral":True,"is_hot":True,"br_status":"Não Vendido","growth":"+167%","opportunity":93,"platform":"AliExpress DS","images":["https://ae01.alicdn.com/kf/Sr7g8h9i0j1k2l/Recovery-Slides.jpg"],"tags":["recovery","conforto","atleta"],"top_priority":True},
    {"title":"Garrafa Térmica 1L Aço Inox 24h","category":"Esporte","price_usd":9.50,"orders_count":312000,"score":87,"markup":3.9,"is_viral":False,"is_hot":False,"br_status":"Já Vendido","growth":"+42%","opportunity":63,"platform":"AliExpress DS","images":["https://ae01.alicdn.com/kf/Ss8h9i0j1k2l3m/Thermal-Bottle.jpg"],"tags":["hidratação","inox","sustentável"]},

    # ─── PET ──────────────────────────────────────────────────────────────────
    {"title":"Bebedouro Elétrico Pet Filtro Silencioso 2.4L","category":"Pet","price_usd":13.90,"orders_count":198000,"score":91,"markup":4.2,"is_viral":True,"is_hot":True,"br_status":"Não Vendido","growth":"+178%","opportunity":94,"platform":"AliExpress DS","images":["https://ae01.alicdn.com/kf/St9i0j1k2l3m4n/Pet-Water-Fountain.jpg"],"tags":["pet","cachorro","gato"],"top_priority":True},
    {"title":"GPS Tracker Pet Coleira Anti-Perda Tempo Real","category":"Pet","price_usd":19.90,"orders_count":156000,"score":90,"markup":3.7,"is_viral":True,"is_hot":True,"br_status":"Não Vendido","growth":"+156%","opportunity":93,"platform":"AliExpress DS","images":["https://ae01.alicdn.com/kf/Su0j1k2l3m4n5o/Pet-GPS.jpg"],"tags":["gps","segurança","pet"],"top_priority":True},
    {"title":"Escova Elétrica Massagem Pet Banho Seco","category":"Pet","price_usd":11.50,"orders_count":134000,"score":87,"markup":4.1,"is_viral":False,"is_hot":True,"br_status":"Não Vendido","growth":"+121%","opportunity":89,"platform":"AliExpress DS","images":["https://ae01.alicdn.com/kf/Sv1k2l3m4n5o6p/Pet-Brush.jpg"],"tags":["grooming","pet","escova"]},

    # ─── ACESSÓRIOS & MODA ────────────────────────────────────────────────────
    {"title":"Bolsa Organizadora Viagem Impermeável 7pcs","category":"Acessórios","price_usd":12.90,"orders_count":189000,"score":87,"markup":4.0,"is_viral":False,"is_hot":False,"br_status":"Não Vendido","growth":"+82%","opportunity":81,"platform":"AliExpress DS","images":["https://ae01.alicdn.com/kf/Sw2l3m4n5o6p7q/Travel-Organizer.jpg"],"tags":["viagem","mala","organização"]},
    {"title":"Mochila Anti-Furto USB Smart 30L Impermeável","category":"Acessórios","price_usd":24.50,"orders_count":234000,"score":91,"markup":3.4,"is_viral":True,"is_hot":True,"br_status":"Pouco Vendido","growth":"+97%","opportunity":84,"platform":"AliExpress DS","images":["https://ae01.alicdn.com/kf/Sx3m4n5o6p7q8r/Smart-Backpack.jpg"],"tags":["mochila","usb","anti-furto"]},
    {"title":"Pulseira Fitness Estilo Apple Watch Ultra Clone","category":"Acessórios","price_usd":16.80,"orders_count":312000,"score":90,"markup":3.8,"is_viral":True,"is_hot":True,"br_status":"Já Vendido","growth":"+62%","opportunity":70,"platform":"AliExpress DS","images":["https://ae01.alicdn.com/kf/Sy4n5o6p7q8r9s/Fitness-Band.jpg"],"tags":["smartwatch","fitness","estilo"]},
    {"title":"Carteira Slim RFID Bloqueio Couro Vegano","category":"Acessórios","price_usd":7.90,"orders_count":167000,"score":86,"markup":4.5,"is_viral":False,"is_hot":False,"br_status":"Não Vendido","growth":"+74%","opportunity":80,"platform":"AliExpress DS","images":["https://ae01.alicdn.com/kf/Sz5o6p7q8r9s0t/RFID-Wallet.jpg"],"tags":["carteira","rfid","segurança"]},
    {"title":"Óculos de Sol Polarizado UV400 Hexagonal","category":"Acessórios","price_usd":8.50,"orders_count":198000,"score":85,"markup":4.8,"is_viral":False,"is_hot":False,"br_status":"Não Vendido","growth":"+68%","opportunity":79,"platform":"AliExpress DS","images":["https://ae01.alicdn.com/kf/S05p6q7r8s9t0u/Hexagonal-Sunglasses.jpg"],"tags":["óculos","moda","verão"]},

    # ─── BEBÊ & INFANTIL ──────────────────────────────────────────────────────
    {"title":"Monitor Bebê WiFi Câmera 1080p Night Vision","category":"Casa","price_usd":29.00,"orders_count":145000,"score":91,"markup":3.5,"is_viral":True,"is_hot":True,"br_status":"Não Vendido","growth":"+134%","opportunity":92,"platform":"AliExpress DS","images":["https://ae01.alicdn.com/kf/S16q7r8s9t0u1v/Baby-Monitor.jpg"],"tags":["bebê","câmera","segurança"],"top_priority":True},
    {"title":"Babador Silicone com Bolso Autoalimentação","category":"Bebê","price_usd":5.20,"orders_count":212000,"score":87,"markup":5.0,"is_viral":False,"is_hot":False,"br_status":"Não Vendido","growth":"+86%","opportunity":83,"platform":"AliExpress DS","images":["https://ae01.alicdn.com/kf/S27r8s9t0u1v2w/Silicone-Bib.jpg"],"tags":["bebê","silicone","alimentação"]},

    # ─── HOME OFFICE ──────────────────────────────────────────────────────────
    {"title":"Webcam 4K Autofoco Ring Light Integrada","category":"Eletrônicos","price_usd":35.00,"orders_count":178000,"score":92,"markup":3.2,"is_viral":True,"is_hot":True,"br_status":"Não Vendido","growth":"+143%","opportunity":91,"platform":"AliExpress DS","images":["https://ae01.alicdn.com/kf/S38s9t0u1v2w3x/4K-Webcam.jpg"],"tags":["webcam","home office","streaming"],"top_priority":True},
    {"title":"Teclado Mecânico Wireless RGB 87 Teclas","category":"Eletrônicos","price_usd":27.50,"orders_count":234000,"score":91,"markup":3.3,"is_viral":True,"is_hot":True,"br_status":"Pouco Vendido","growth":"+108%","opportunity":83,"platform":"AliExpress DS","images":["https://ae01.alicdn.com/kf/S49t0u1v2w3x4y/Mech-Keyboard.jpg"],"tags":["teclado","gamer","setup"]},
    {"title":"Mouse Pad XL LED RGB 900x400mm","category":"Eletrônicos","price_usd":10.50,"orders_count":289000,"score":87,"markup":4.2,"is_viral":False,"is_hot":True,"br_status":"Pouco Vendido","growth":"+79%","opportunity":78,"platform":"AliExpress DS","images":["https://ae01.alicdn.com/kf/S50u1v2w3x4y5z/XL-Mousepad.jpg"],"tags":["gamer","setup","rgb"]},
    {"title":"Suporte Notebook Ergonômico Ajustável Alumínio","category":"Casa","price_usd":13.90,"orders_count":178000,"score":88,"markup":3.9,"is_viral":False,"is_hot":False,"br_status":"Não Vendido","growth":"+91%","opportunity":85,"platform":"AliExpress DS","images":["https://ae01.alicdn.com/kf/S61v2w3x4y5z6a/Laptop-Stand.jpg"],"tags":["ergonômico","home office","alumínio"],"top_priority":True},

    # ─── VEÍCULOS & ACESSÓRIOS ────────────────────────────────────────────────
    {"title":"Câmera Ré 4K Wireless Sem Fio Universal","category":"Acessórios","price_usd":18.50,"orders_count":156000,"score":89,"markup":3.7,"is_viral":False,"is_hot":True,"br_status":"Não Vendido","growth":"+112%","opportunity":88,"platform":"AliExpress DS","images":["https://ae01.alicdn.com/kf/S72w3x4y5z6a7b/Rear-Camera.jpg"],"tags":["carro","câmera","segurança"],"top_priority":True},
    {"title":"Suporte Celular Carro Ventosa Magnético 360°","category":"Acessórios","price_usd":5.50,"orders_count":312000,"score":84,"markup":5.5,"is_viral":False,"is_hot":False,"br_status":"Já Vendido","growth":"+38%","opportunity":61,"platform":"AliExpress DS","images":["https://ae01.alicdn.com/kf/S83x4y5z6a7b8c/Car-Mount.jpg"],"tags":["carro","suporte","magnético"]},
    {"title":"Compressor Portátil 150PSI Digital USB-C","category":"Acessórios","price_usd":21.00,"orders_count":134000,"score":88,"markup":3.6,"is_viral":True,"is_hot":True,"br_status":"Não Vendido","growth":"+129%","opportunity":90,"platform":"AliExpress DS","images":["https://ae01.alicdn.com/kf/S94y5z6a7b8c9d/Tyre-Inflator.jpg"],"tags":["carro","pneu","portátil"],"top_priority":True},

    # ─── ILUMINAÇÃO & DECO ────────────────────────────────────────────────────
    {"title":"Lâmpada Neon Flex Personalizada USB 2m","category":"Casa","price_usd":12.50,"orders_count":198000,"score":88,"markup":4.3,"is_viral":True,"is_hot":True,"br_status":"Não Vendido","growth":"+167%","opportunity":92,"platform":"AliExpress DS","images":["https://ae01.alicdn.com/kf/S05z6a7b8c9d0e/Neon-Flex.jpg"],"tags":["neon","decoração","gaming"],"top_priority":True},
    {"title":"Fita LED RGB 5050 10m WiFi Alexa App","category":"Casa","price_usd":9.90,"orders_count":345000,"score":87,"markup":4.0,"is_viral":False,"is_hot":True,"br_status":"Pouco Vendido","growth":"+72%","opportunity":76,"platform":"AliExpress DS","images":["https://ae01.alicdn.com/kf/S16a7b8c9d0e1f/LED-Strip.jpg"],"tags":["led","rgb","smart home"]},
    {"title":"Luminária Mesa LED Wireless Toque Dimmer","category":"Casa","price_usd":14.90,"orders_count":167000,"score":87,"markup":3.8,"is_viral":False,"is_hot":False,"br_status":"Não Vendido","growth":"+88%","opportunity":83,"platform":"AliExpress DS","images":["https://ae01.alicdn.com/kf/S27b8c9d0e1f2g/Desk-Lamp.jpg"],"tags":["luminária","wireless","home office"]},

    # ─── IMPRESSÃO 3D & CRIADORES ─────────────────────────────────────────────
    {"title":"Caneta 3D Profissional PLA/ABS Display LCD","category":"Eletrônicos","price_usd":16.90,"orders_count":123000,"score":87,"markup":4.1,"is_viral":True,"is_hot":True,"br_status":"Não Vendido","growth":"+144%","opportunity":91,"platform":"AliExpress DS","images":["https://ae01.alicdn.com/kf/S38c9d0e1f2g3h/3D-Pen.jpg"],"tags":["criativo","3d","crianças"],"top_priority":True},
    {"title":"Estabilizador Gimbal 3 Eixos Smartphone","category":"Eletrônicos","price_usd":26.00,"orders_count":189000,"score":92,"markup":3.5,"is_viral":True,"is_hot":True,"br_status":"Não Vendido","growth":"+138%","opportunity":92,"platform":"AliExpress DS","images":["https://ae01.alicdn.com/kf/S49d0e1f2g3h4i/Phone-Gimbal.jpg"],"tags":["vídeo","creator","gimbal"],"top_priority":True},
]


async def get_global_trendsetters(limit: int = 50, top_priority_only: bool = False) -> list:
    """Return curated list of global trend products not saturated in Brazil."""
    products = GLOBAL_TRENDSETTERS
    if top_priority_only:
        products = [p for p in products if p.get("top_priority")]
    return products[:limit]
