"""
Popula o banco com 10 produtos de exemplo para demonstração do NEXO.
Execute: python scripts/seed_products.py
"""
import asyncio, sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from database.db import init_db, upsert_products

PRODUCTS = [
    {
        "product_id": "nexo-seed-pistola-massagem",
        "title": "Pistola de Massagem Muscular Portátil",
        "category": "Saúde",
        "platform": "aliexpress",
        "price_usd": 12.99,
        "cost_brl": 79.24,
        "freight_brl": 35.0,
        "tax_brl": 15.85,
        "total_cost_brl": 130.09,
        "suggested_sell_price": 546.38,
        "markup": 4.2,
        "orders_count": 85000,
        "rating": 4.8,
        "br_status": "Pouco Vendido",
        "score": 87,
        "images": ["https://ae01.alicdn.com/kf/S8b5e0c5a63684e0ead7c0e0e1b7b3e3cJ.jpg"],
        "image_url": "https://ae01.alicdn.com/kf/S8b5e0c5a63684e0ead7c0e0e1b7b3e3cJ.jpg",
        "product_url": "https://www.aliexpress.com/wholesale?SearchText=pistola+massagem",
        "supplier_name": "AliExpress",
        "growth": "+45%",
        "is_new": True,
        "targeting_suggestion": ["Musculação", "CrossFit", "Fisioterapia", "Esporte e Fitness", "Recuperação muscular"],
        "copy_suggestion": "🔥 Chega de dores musculares! A Pistola de Massagem Profissional relaxa qualquer músculo em segundos. Usada por atletas e fisioterapeutas. Aproveite o frete grátis hoje! 💪",
    },
    {
        "product_id": "nexo-seed-escova-alisadora",
        "title": "Escova Alisadora Rotativa para Cabelo",
        "category": "Beleza",
        "platform": "aliexpress",
        "price_usd": 8.50,
        "cost_brl": 51.85,
        "freight_brl": 35.0,
        "tax_brl": 10.37,
        "total_cost_brl": 97.22,
        "suggested_sell_price": 495.82,
        "markup": 5.1,
        "orders_count": 120000,
        "rating": 4.7,
        "br_status": "Pouco Vendido",
        "score": 92,
        "images": ["https://ae01.alicdn.com/kf/S9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4y.jpg"],
        "image_url": "https://ae01.alicdn.com/kf/S9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4y.jpg",
        "product_url": "https://www.aliexpress.com/wholesale?SearchText=escova+alisadora",
        "supplier_name": "AliExpress",
        "growth": "+62%",
        "is_new": True,
        "targeting_suggestion": ["Cuidados com o cabelo", "Beleza e cosméticos", "Mulheres 25-45", "Salão de beleza em casa", "Alisamento capilar"],
        "copy_suggestion": "✨ Cabelos lisos e brilhosos em apenas 5 minutos! A Escova Alisadora Rotativa 3 em 1 seca, alinha e dá volume ao mesmo tempo. Sem frizz, sem complicação! Peça já! 💁‍♀️",
    },
    {
        "product_id": "nexo-seed-mascara-led",
        "title": "Máscara LED Facial para Rejuvenescimento",
        "category": "Beleza",
        "platform": "aliexpress",
        "price_usd": 11.20,
        "cost_brl": 68.32,
        "freight_brl": 35.0,
        "tax_brl": 13.66,
        "total_cost_brl": 116.98,
        "suggested_sell_price": 561.50,
        "markup": 4.8,
        "orders_count": 65000,
        "rating": 4.6,
        "br_status": "Não Vendido",
        "score": 89,
        "images": ["https://ae01.alicdn.com/kf/Sc3d4e5f6a7b8c9d0e1f2a3b4c5d6e7fx.jpg"],
        "image_url": "https://ae01.alicdn.com/kf/Sc3d4e5f6a7b8c9d0e1f2a3b4c5d6e7fx.jpg",
        "product_url": "https://www.aliexpress.com/wholesale?SearchText=mascara+led+facial",
        "supplier_name": "AliExpress",
        "growth": "+78%",
        "is_new": True,
        "targeting_suggestion": ["Anti-envelhecimento", "Skincare", "Dermatologia estética", "Bem-estar feminino", "Beleza em casa"],
        "copy_suggestion": "💎 Pele jovem sem sair de casa! A Máscara LED Facial usa a mesma tecnologia de clínicas de estética. 7 cores para tratar manchas, acne e rugas. Resultados visíveis em 30 dias! 🌟",
    },
    {
        "product_id": "nexo-seed-brinquedo-gato",
        "title": "Brinquedo Automático para Gatos com Pena",
        "category": "Pet",
        "platform": "aliexpress",
        "price_usd": 5.30,
        "cost_brl": 32.33,
        "freight_brl": 35.0,
        "tax_brl": 6.47,
        "total_cost_brl": 73.80,
        "suggested_sell_price": 405.90,
        "markup": 5.5,
        "orders_count": 95000,
        "rating": 4.9,
        "br_status": "Não Vendido",
        "score": 94,
        "images": ["https://ae01.alicdn.com/kf/S4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9z.jpg"],
        "image_url": "https://ae01.alicdn.com/kf/S4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9z.jpg",
        "product_url": "https://www.aliexpress.com/wholesale?SearchText=brinquedo+automatico+gato",
        "supplier_name": "AliExpress",
        "growth": "+120%",
        "is_new": True,
        "targeting_suggestion": ["Donos de gatos", "Bem-estar animal", "Pet shop", "Gatos domésticos", "Animais de estimação"],
        "copy_suggestion": "🐱 Seu gato vai enlouquecer! O Brinquedo Automático com pena gira sozinho e mantém seu gato ativo por horas. Recarregável, silencioso e seguro. Seu bichinho merece! 🐾",
    },
    {
        "product_id": "nexo-seed-mini-mixer",
        "title": "Mini Mixer Portátil para Shakes e Sucos",
        "category": "Cozinha",
        "platform": "aliexpress",
        "price_usd": 7.80,
        "cost_brl": 47.58,
        "freight_brl": 35.0,
        "tax_brl": 9.52,
        "total_cost_brl": 92.10,
        "suggested_sell_price": 395.83,
        "markup": 4.3,
        "orders_count": 200000,
        "rating": 4.7,
        "br_status": "Pouco Vendido",
        "score": 85,
        "images": ["https://ae01.alicdn.com/kf/S4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9p.jpg"],
        "image_url": "https://ae01.alicdn.com/kf/S4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9p.jpg",
        "product_url": "https://www.aliexpress.com/wholesale?SearchText=mini+mixer+portatil",
        "supplier_name": "AliExpress",
        "growth": "+35%",
        "is_new": True,
        "targeting_suggestion": ["Vida saudável", "Academia e fitness", "Nutrição", "Perda de peso", "Alimentação saudável"],
        "copy_suggestion": "🥤 Shakes e vitaminas em qualquer lugar! O Mini Mixer Portátil USB bate até gelo em segundos. Cabe na bolsa, vai à academia, ao trabalho e às viagens. Peça o seu agora! 💪",
    },
    {
        "product_id": "nexo-seed-suporte-magnetico",
        "title": "Suporte Magnético para Celular no Carro",
        "category": "Acessórios",
        "platform": "aliexpress",
        "price_usd": 3.50,
        "cost_brl": 21.35,
        "freight_brl": 35.0,
        "tax_brl": 4.27,
        "total_cost_brl": 60.62,
        "suggested_sell_price": 375.84,
        "markup": 6.2,
        "orders_count": 300000,
        "rating": 4.8,
        "br_status": "Já Vendido",
        "score": 78,
        "images": ["https://ae01.alicdn.com/kf/S9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4m.jpg"],
        "image_url": "https://ae01.alicdn.com/kf/S9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4m.jpg",
        "product_url": "https://www.aliexpress.com/wholesale?SearchText=suporte+magnetico+carro",
        "supplier_name": "AliExpress",
        "growth": "+18%",
        "is_new": False,
        "targeting_suggestion": ["Motoristas", "Aplicativo de entrega", "Uber e 99", "Acessórios automotivos", "Tecnologia mobile"],
        "copy_suggestion": "🚗 Nunca mais perca a rota! O Suporte Magnético 360° para carro fixa qualquer celular na posição ideal. Instalação em 5 segundos, compatível com todos os modelos. Corra para o seu! 📱",
    },
    {
        "product_id": "nexo-seed-massageador-joelho",
        "title": "Massageador Elétrico para Joelho",
        "category": "Saúde",
        "platform": "aliexpress",
        "price_usd": 15.00,
        "cost_brl": 91.50,
        "freight_brl": 35.0,
        "tax_brl": 18.30,
        "total_cost_brl": 144.80,
        "suggested_sell_price": 550.24,
        "markup": 3.8,
        "orders_count": 45000,
        "rating": 4.6,
        "br_status": "Não Vendido",
        "score": 86,
        "images": ["https://ae01.alicdn.com/kf/S7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2k.jpg"],
        "image_url": "https://ae01.alicdn.com/kf/S7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2k.jpg",
        "product_url": "https://www.aliexpress.com/wholesale?SearchText=massageador+eletrico+joelho",
        "supplier_name": "AliExpress",
        "growth": "+55%",
        "is_new": True,
        "targeting_suggestion": ["Artrite e artrose", "Idosos ativos", "Fisioterapia em casa", "Dores articulares", "Saúde e bem-estar"],
        "copy_suggestion": "🦵 Chega de dor no joelho! O Massageador Elétrico com aquecimento e vibração alivia a dor em minutos. Indicado para artrose, pós-cirurgia e esporte. Sem dor, com qualidade de vida! ✅",
    },
    {
        "product_id": "nexo-seed-corretor-postura",
        "title": "Corretor de Postura Ajustável",
        "category": "Saúde",
        "platform": "aliexpress",
        "price_usd": 6.20,
        "cost_brl": 37.82,
        "freight_brl": 35.0,
        "tax_brl": 7.56,
        "total_cost_brl": 80.38,
        "suggested_sell_price": 401.90,
        "markup": 5.0,
        "orders_count": 180000,
        "rating": 4.5,
        "br_status": "Pouco Vendido",
        "score": 83,
        "images": ["https://ae01.alicdn.com/kf/S3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8p.jpg"],
        "image_url": "https://ae01.alicdn.com/kf/S3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8p.jpg",
        "product_url": "https://www.aliexpress.com/wholesale?SearchText=corretor+postura",
        "supplier_name": "AliExpress",
        "growth": "+40%",
        "is_new": True,
        "targeting_suggestion": ["Trabalho home office", "Coluna e postura", "Fisioterapia", "Dores nas costas", "Ergonomia no trabalho"],
        "copy_suggestion": "🏋️ Postura correta em 2 semanas! O Corretor de Postura Ajustável alinha sua coluna enquanto você trabalha ou estuda. Discreto, confortável e eficaz. Cuide da sua saúde agora! 💚",
    },
    {
        "product_id": "nexo-seed-lampada-uv",
        "title": "Lâmpada UV para Unhas Gel Profissional",
        "category": "Beleza",
        "platform": "aliexpress",
        "price_usd": 9.90,
        "cost_brl": 60.39,
        "freight_brl": 35.0,
        "tax_brl": 12.08,
        "total_cost_brl": 107.47,
        "suggested_sell_price": 483.62,
        "markup": 4.5,
        "orders_count": 250000,
        "rating": 4.8,
        "br_status": "Já Vendido",
        "score": 80,
        "images": ["https://ae01.alicdn.com/kf/S0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5u.jpg"],
        "image_url": "https://ae01.alicdn.com/kf/S0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5u.jpg",
        "product_url": "https://www.aliexpress.com/wholesale?SearchText=lampada+uv+unhas",
        "supplier_name": "AliExpress",
        "growth": "+22%",
        "is_new": False,
        "targeting_suggestion": ["Nail art", "Manicure profissional", "Beleza feminina", "Unhas de gel em casa", "Autocuidado"],
        "copy_suggestion": "💅 Manicure profissional em casa! A Lâmpada UV 54W cura qualquer gel em apenas 30 segundos. Timer automático, compatível com todas as marcas. Economize na manicure todo mês! ✨",
    },
    {
        "product_id": "nexo-seed-garrafa-pet",
        "title": "Garrafa de Água Portátil para Pets",
        "category": "Pet",
        "platform": "aliexpress",
        "price_usd": 4.80,
        "cost_brl": 29.28,
        "freight_brl": 35.0,
        "tax_brl": 5.86,
        "total_cost_brl": 70.14,
        "suggested_sell_price": 406.81,
        "markup": 5.8,
        "orders_count": 110000,
        "rating": 4.9,
        "br_status": "Não Vendido",
        "score": 91,
        "images": ["https://ae01.alicdn.com/kf/S4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9w.jpg"],
        "image_url": "https://ae01.alicdn.com/kf/S4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9w.jpg",
        "product_url": "https://www.aliexpress.com/wholesale?SearchText=garrafa+agua+pet",
        "supplier_name": "AliExpress",
        "growth": "+88%",
        "is_new": True,
        "targeting_suggestion": ["Donos de cachorros", "Passeios com pets", "Vida ativa com animais", "Pet lovers", "Bem-estar animal"],
        "copy_suggestion": "🐕 Seu pet nunca mais vai ficar com sede! A Garrafa Portátil 350ml tem botão de liberação de água integrado. Perfeita para passeios, viagens e a praça. Seu melhor amigo merece! 💙",
    },
]


async def main():
    print("Inicializando banco de dados...")
    await init_db()
    print(f"Inserindo {len(PRODUCTS)} produtos...")
    await upsert_products(PRODUCTS)
    print("✅ Seed concluído com sucesso!")


if __name__ == "__main__":
    asyncio.run(main())
